#!/bin/sh
# daemontools run script. Venus OS supervises this with svscan; if the
# process exits, it is restarted automatically.

exec 2>&1

export UI_PORT="${UI_PORT:-8088}"

exec /data/ruuvi-victron-control/ruuvi-control
